(define x 2)
(define y 8)
(define z 7)

(describe arithmetic-test
    (== (+ 5 5) 10)
    (== (- 10 7) 3)
    (== (* 2 4)  8)
    (== (/ 25 5) 5)
    (== (% 7 5)  2))

(describe condition-test
    (== (< x y)  #t)
    (== (< y z)  #f)
    (== (> x y)  #f)
    (== (> z x)  #t)
    (== (<= x 2) #t)
    (== (>= z 7) #t)
    (== (!= x x) #f)
    (== (!= 2 x) #f)
    (== (!= 2 3) #t)
    (== (! #f)   #t)
    (== (! #t)   #f)
    (== (or #f #f)     #f)
    (== (or #f #f #t)  #t)
    (== (and #t #f #t) #f)
    (== (and #t #t #t) #t)
    (== (or (> x z) (> y z))  #t)
    (== (and (> x z) (>y z))  #f))